# Connection configuration for 4 nodes raspberrypi cluster
NUM_NODES: 4 # set 1 if you only install on one raspberry pi
Path:
    FILE_PATH: ./Files # configure files
    TEMP_FILES: ./temp_files # file download
    SSH_KEY_PATH: ./connection # generated ssh key
Connection:
    HOST_IP:
        - '192.168.1.101' # Master
        - '192.168.1.105' # Slave1
        - '192.168.1.104' # Slave2
        - '192.168.1.110' # Slave3
    Login:
        USER: pi
        PASSWORD: raspberry
    CONN_MODE: IP # Enter either 'IP' or 'HOSTNAME'
    # USE IP MODE BEFORE YOU SETUP HOSTNAME FOR EACH NODE (you can use my "set-hostname" function)
    # OR MODIFY hard-coded 'master' to 'raspberrypi' in fabfile.py (WHICH IS DEFAULT HOSTNAME FOR RASPBERRY PI)
    # IF YOU ONLY RUN ON SINGLE NODE
    DISABLE_SSH_KEY: TRUE
    # If you didn't bind ssh-key for your server (e.g. Aliyun). Use TRUE.
    # If your server need ssh-key beforhand (e.g. GCP, AWS). Use FALSE.
    # And make sure you've put the key under the SSH_KEY_PATH or you can modify DEFAULT_SSHKEY in fabfile.py directly.
Hadoop:
    Connection:
        Login:
            HADOOP_GROUP: hadoop
            HADOOP_USER: hduser
            HADOOP_PASSWORD: hadoop
    
